name: Build Vite and Push to Docs via SSH

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 4: Сборка проекта
      - name: Build Vite project
        run: npm run build

      # Шаг 5: Настройка SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Шаг 6: Настройка Git
      - name: Configure Git
        run: |
          git config --global garaev-vadim-m "github-actions[bot]"
          git config --global garaev.v.m@icloud.com "github-actions[bot]@users.noreply.github.com"

      # Шаг 7: Добавление изменений и коммит
      - name: Commit and push changes
        run: |
          git add docs
          git commit -m "Update built files in docs" || echo "No changes to commit"
          git push git@github.com:garaev-vadim-m/digital.git master
